### ISSUE TITLE
Plugin for MPS 2017

### ISSUE THREAD

**Issue by mikheyev** [CampagneLaboratory/NextflowWorkbench#7]
I would love to give Nextflow Workbench a try, but the installation instructions no longer work, and it looks like the [latest version of the plugin](https://plugins.jetbrains.com/plugin/7895-org-campagnelab-nextflowworkbench) is not compatible with the current release. Do you intend to update the plugin?

**Comment by fac2003** [comment]
We are waiting for itemis plugins (i.e., richtext) to be released on the latest version of MPS. Because these plugins are part of the mbeddr platform, they are only deploying against versions of MPS tested against mbeddr. 

What do you mean specifically by installation instructions no longer work? I installed NW this week on a new laptop and had no issue (best to follow exactly the instructions).

**Comment by mikheyev** [comment]
I have tried the installation instructions, but there is no mbeddr plugin found in the plugins list. I tried to download the latest version of the plugin from the link above, but it doesn't load properly by itself.

I am using the following configuration:
JetBrains MPS 2017.1
Build #MPS-171.1216, built on April 27, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

**Comment by manuelesimi** [comment]
As stated in the installation instructions, the current NextflowWorkbench release supports MPS 3.4.3. You are trying to install it in MPS 2017.1, it won't work.  We can't support this version of MPS because the mdeddr plugins we rely on do not support it yet.

**Comment by mikheyev** [comment]
OK, all clear now. Sorry my question was probably not clear -- I was wondering whether the plugin will be updated to work with the current version of MPS. Now I understand that you are waiting for the plugins you depend on to be updated.

**Comment by multimeric** [comment]
Has there been any progress with this? I'm not entirely sure which plugins need to be updated, but neither `mbeddr` nor `NextflowWorkbench` can be installed on recent versions of MPS

**Comment by fac2003** [comment]
NextflowWorkbench has been updated to 2018.1 (@manuelesimi should probably update the installation instructions to reflect this upgrade). You should be able to find NW in the plugin repo using this version. 
NW will always lag behind the latest MPS build, like most tools upgrading to a new platform takes time. 

I would add that this work is not funded at this time, and the lab has closed last month, so maintenance going forward is not a given.

**Comment by multimeric** [comment]
Great! Can you point me to where the plugin is? Should it be [here](https://plugins.jetbrains.com/plugin/7895-org-campagnelab-nextflowworkbench) or is the actual in-app plugin browser different?

**Comment by manuelesimi** [comment]
Sorry, there has been a delay to publish the updated plugin. We plan to do it by the end of this week. The new version supporting MPS2018.1.1 is 1.8.0. I will update this issue as soon as it available on the MPS repository.

**Comment by manuelesimi** [comment]
NextflowWorkbench 1.8.0 has been released. Please, follow the updated instructions to install the new plugin [here](http://campagnelab.org/software/nextflow-workbench/installation-instructions/) as the required configuration has changed.
